version: "3"

services:
  food_ordering:
    build:
      context: .
    ports:
      - 8011:8011
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8011
    depends_on:
      - database
    env_file:
      - .env

  database:
    restart: always
    image: kartoza/postgis:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/app/logs
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  postgres_data:
